# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wang Jie
#subtitle: To be an artist-enginner
subtitle: TO BE AN ARTIST-ENGINNER
# description: Wang Jie's blog
description: Hi! Welcome to Wang Jie's blog. This blog has been migrated from <a href='http://www.cnblogs.com/tiantianbyconan/'>cnblog</a>.
author: Wang Jie
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://yoursite.com
url: http://blog.wangjiegulu.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: next
# theme: Hacker

# https://github.com/haojen/hexo-theme-Anisina
# theme: Anisina
theme: cactus

# https://github.com/cofess/hexo-theme-pure
# theme: pure


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:wangjiegulu/wangjiegulu.github.com.git
  branch: master

# rss
feed:
  type: atom
  path: feed.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '


# for cactus theme
# theme_config:
#   colorscheme: white

