menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: blog-wangjiegulu-com

# google analytics
googleTrackId:
